# Generated by Django 5.2.12 on 2026-04-01 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='任務名稱 (例: 每日台股盤後數據)', max_length=255)),
                ('adapter_type', models.CharField(help_text='指定適配器類型 (例: twse, yahoo)', max_length=50)),
                ('symbols', models.JSONField(help_text='股票代碼清單 ["2330", "2317"]')),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('RUNNING', 'Running'), ('FAILED', 'Failed')], default='IDLE', help_text='最後一次執行結果', max_length=20)),
                ('schedule_time', models.TimeField(blank=True, help_text='使用者定義的執行時間', null=True)),
                ('last_run_at', models.DateTimeField(blank=True, help_text='最後一次啟動時間', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='是否啟用該排程')),
            ],
        ),
        migrations.CreateModel(
            name='StockDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, help_text='股票代碼 (例: 2330, AAPL)', max_length=50)),
                ('name', models.CharField(help_text='公司名稱 (例: 台積電, Tesla Inc.)', max_length=255)),
                ('market', models.CharField(choices=[('twse', 'Taiwan Stock Exchange'), ('yahoo', 'Yahoo Global')], db_index=True, max_length=50)),
                ('alias', models.CharField(blank=True, help_text='搜尋別名 (例: TSMC)', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Stock Directories',
                'unique_together': {('ticker', 'market')},
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(help_text='股票代碼', max_length=50)),
                ('market_date', models.DateField(help_text='市場歷史日期 (K線圖時間點)')),
                ('open_price', models.DecimalField(decimal_places=4, help_text='開盤價', max_digits=12)),
                ('high_price', models.DecimalField(decimal_places=4, help_text='最高價', max_digits=12)),
                ('low_price', models.DecimalField(decimal_places=4, help_text='最低價', max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=4, help_text='收盤價', max_digits=12)),
                ('volume', models.BigIntegerField(help_text='成交量')),
                ('source', models.CharField(help_text='數據來源 (例: yahoo, twse)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='存檔時間')),
            ],
            options={
                'ordering': ['-market_date'],
                'unique_together': {('ticker', 'market_date', 'source')},
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='STARTED', max_length=20)),
                ('records_count', models.IntegerField(default=0, help_text='本次成功處理的資料筆數')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='開始執行時間')),
                ('finished_at', models.DateTimeField(blank=True, help_text='完成時間', null=True)),
                ('error_log', models.TextField(blank=True, help_text='失敗時的錯誤訊息', null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='stocks.stocktask')),
            ],
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, default='ERROR', max_length=20)),
                ('source', models.CharField(help_text='來源模組 (e.g. stocks.tasks)', max_length=255)),
                ('message', models.TextField(help_text='錯誤摘要')),
                ('traceback', models.TextField(blank=True, default='', help_text='完整的 traceback')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('task', models.ForeignKey(blank=True, help_text='關聯的數據任務（如適用）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to='stocks.stocktask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
